### ISSUE TITLE
Code crashes: Q/U data not converted to complex?

### ISSUE THREAD

**Issue by Cameron-Van-Eck** [sabourke/pyrmsynth_lite#9]
Hello!

I've been trying to work with pyRMsynth-lite to compare it to the results I get with the RM synthesis package I maintain (RM-tools, https://github.com/CIRADA-Tools/RM). Shinsuke Ideguchi reported some differences between the outputs of the two codes, so I want to understand them.

But before that, I'm struggling to get pyRMsynth-lite to run. From looking at the code, I deduced that it wants FITS files with 4 axes: RA, DEC, STOKES, FREQ. I created such a file, with NAXIS3=2 (a Stokes Q cube and a Stokes U cube). I'll append the FITS header at the bottom, for completeness.

When I try to run pyRMsynth on this file, I get the resulting error message:
```
cvaneck:~/Projects/CIRADA_POL/RM-tools_testing/pyRMsynthlite$ ~/.local/bin/pyrmsynth_lite.py rmsynth.par litecube.fits -p -a
Parsing parameter file...
Loading data...
RMSynth Initializing... Complete.
Doing RM synthesis
Traceback (most recent call last):
 File "/Users/cvaneck/.local/bin/pyrmsynth_lite.py", line 445, in <module>
   main()
 File "/Users/cvaneck/.local/bin/pyrmsynth_lite.py", line 335, in main
   rmc.residual_map = rms.compute_dirty_image(non_masked_data[i])
 File "/Users/cvaneck/.local/lib/python2.7/site-packages/rm_tools/rm_tools.py", line 162, in compute_dirty_image
   pol = pol * self.weights_nonuni
ValueError: operands could not be broadcast together with shapes (488,2) (488,)
```

I tracked down the source of the problem. After all the data manipulations to get the data into the desired shape, the result is that the data supplied to the rm_tools functions (pyRMsynth-lite.py lines 335 and 348) have the shape of a (488,2) array, meaning both Stokes parameters are kept separate. Looking at the documentation for the rm_tools.compute_dirty_image() function, it expects a 1D array of complex values (i.e., the Stokes parameters combined into the complex polarization).

Have I misunderstood the expected structure of the input data: should be already be complex polarization? Have I structured my input file wrong in some other respect?

I've also noticed something disturbing while seeing if I could fix this easily. In line 309, the data is changed and I don't understand why or how. Before running line 309: 
```
data[0,0,0]
Out[35]: array([-0.44944182, -1.73361997])
non_masked_data[0,0]
Out[34]: array([-0.44944182, -1.73361997])
```
and after running line 309:
```
non_masked_data[0,0]
Out[37]: array([-1.72472084-4.9101868e-17j, -1.96670246+2.4415086e+07j])
```
The values of the real components are not the same, and the values of the imaginary components show very random orders of magnitude. The `.view(dtype=">c8")` on line 309 changes the data in a way I don't understand and which disturbs me greatly.

I've made a temporary fix to my copy, changing line 307 to `non_masked_data = data[data_selection][:,:,0]+1j*data[data_selection][:,:,1]` and commenting out line 309 (I have no NaNs in my simulation, so it's fine). 

This produces reasonable outputs, so I'm able to proceed with my comparison from there. But I'm concerned that I don't understand why I had to make those changes: is it something weird with my (simulated) data? With the code?

Cheers,
Cameron Van Eck

FITS header:
```
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    4 / number of array dimensions                     
NAXIS1  =                  100                                                  
NAXIS2  =                  100                                                  
NAXIS3  =                    2                                                  
NAXIS4  =                  488                                                  
CTYPE1  = 'RA---SIN'                                                            
CRVAL1  =                   90                                                  
CDELT1  = -0.00027777777777777                                                  
CRPIX1  =                    1                                                  
CUNIT1  = 'deg     '                                                            
CTYPE2  = 'DEC--SIN'                                                            
CRVAL2  =                    0                                                  
CDELT2  = 0.000277777777777777                                                  
CRPIX2  =                    1                                                  
CUNIT2  = 'deg     '                                                            
CTYPE3  = 'STOKES  '                                                            
CRVAL3  =                    2                                                  
CDELT3  =                    1                                                  
CRPIX3  =                    1                                                  
CUNIT3  = ''                                                                    
CTYPE4  = 'FREQ    '                                                            
CRVAL4  =          110000000.0                                                  
CDELT4  =    123203.2854209393                                                  
CRPIX4  =                    1                                                  
CUNIT4  = 'Hz      '                                                            
END                                                 ```

**Comment by mhardcastle** [comment]
I've just encountered exactly the same problem as Cameron on my own simulated data, fixed in the same way. I'm puzzled by this, because the LOFAR DR2 QU cubes obviously have split Q and U, and this code is supposed to work for those.

**Comment by sabourke** [comment]
Hi, I haven't got to look at this yet but from emails I think Cameron figured it out. The issue was that pyrmsynth_lite assumes DR2 data which are 32 bit and it croaks on the 64 bit data which Cameron was trying to process. Is that what you're doing too?

**Comment by sabourke** [comment]
I'll add a check to ensure data is 32bit. My inclination is not to support anything other than DR2 style data - the flexibility in the FITS data format makes its it a pain to handle arbitrary layouts.

**Comment by mhardcastle** [comment]
Yeah, my simulations are producing 64-bit floats. I think I understand why that would cause the second of Cameron's problems, with the view of the numpy array, but not the first. However, your check should solve the problem.
